### ISSUE TITLE
(🐞) mypy 0.940 on Cloud Functions uses Python 3.9 instead of 3.10

### ISSUE THREAD

**Issue by KotlinIsland** [ymyzk/mypy-playground#193]
https://mypy-play.net/?mypy=latest&python=3.10&flags=verbose&gist=b6fe99664ac47465bffa8f11ca3cc84b

Look out the output, for some reason it's using python 3.9

**Comment by ymyzk** [comment]
This shouldn't be a bug. Python version used to run mypy and `--python-version` option given when running mypy can be different.

**Comment by ymyzk** [comment]
OK, then I can update the runtime to Python 3.10.

**Comment by KotlinIsland** [comment]
Whats strange is that the dockerfile says that it uses 3.10 https://github.com/ymyzk/mypy-playground/blob/cd895ca1e6d44339809af9d72fce543e668dc57a/sandbox/docker/0.940/Dockerfile#L1

**Comment by ymyzk** [comment]
Due to infrastructure cost issues, the current mypy-play.net is backed by Cloud Functions rather than Docker. https://cloud.google.com/functions/docs/concepts/python-runtime

It seems we need to wait for GCP to add Python 3.10 support or someone needs to find compute resources to run Docker containers.

**Comment by ymyzk** [comment]
I'm not 100% sure whether it's the root cause or not but GCP rejects to use Python 3.10 and it's not in the support list I shared above:
```
$ RUNTIME=python310 REGION=xxx INVOKER_MEMBER=xxx SERVICE_ACCOUNT=xxx ./deploy.sh 0.941                                                                                                                                            
Deploying 0.941 as mypy-0-941...                                                                                                                                                         
ERROR: (gcloud.functions.deploy) ResponseError: status=[400], code=[Ok], message=[The request has errors
Problems:                                                                                   
runtime:                                                                                                                                                                                 
Incorrect runtime value                                                                                                                                                                  
]                                                                                                                                                                                        
```

**Comment by KotlinIsland** [comment]
https://github.com/python/mypy/issues/12357

**Comment by szunami** [comment]
In the short term, can you hide python 3.10 as a choice if it is not actually supported?

**Comment by szunami** [comment]
In my experience mypy and especially mypy-playground is most helpful for checking syntax / experimenting with different ways of expressing code. If the syntax isn't supported, then it isn't very helpful and perhaps actively misleading. Just my 2 cents.

There might be a middle ground where the UI more loudly calls out this limitation in some way.

Thanks for making this tool, I do appreciate it!

**Comment by KotlinIsland** [comment]
@szunami Mypy should shout out about this case in my opinion, take a look at https://github.com/python/mypy/issues/12357 (and maybe give it a 👍 if you like it)

**Comment by hauntsaninja** [comment]
It seems like GCP claims to have fixed whatever problem in April (after this issue was discussed): https://github.com/GoogleCloudPlatform/buildpacks/commit/9cfe3e2166311f6ded7a7718193d010e417a3e28

Would you be able to retry and see if it works?

Thank you again, I use mypy-play.net on most days :-)

**Comment by ymyzk** [comment]
@hauntsaninja, thanks for sharing the update! I confirmed that we can now run sandbox using Python 3.10 on Cloud Functions. I just updated all sandbox images for mypy 0.920 and later to use Python 3.10.
