### ISSUE TITLE
(🐞) Some emojis are not handled well

### ISSUE THREAD

**Issue by KotlinIsland** [ymyzk/mypy-playground#197]
https://mypy-play.net/?mypy=latest&python=3.10&gist=b2af7e706552b46cc9c402b84be671b3

**Comment by ymyzk** [comment]
This looks like an issue of the editor we're using: https://ace.c9.io/ Please consider opening a ticket on the upstream instead: https://github.com/ajaxorg/ace

**Comment by KotlinIsland** [comment]
https://github.com/ajaxorg/ace/issues/4142
