### ISSUE TITLE
(🎁) Add pylint as an additional tool

### ISSUE THREAD

**Issue by KotlinIsland** [ymyzk/mypy-playground#201]
There is an issue to add additional tools other than mypy(#82), I think pylint would be a great candidate.

https://github.com/PyCQA/pylint/issues/5972

**Comment by ymyzk** [comment]
Thanks for sharing an interesting idea. At this point, I would like to focus on the problem of easy online type checking for Python as I feel we still have space for improvements and I would like to spend my limited resources, such as development & maintenance time and infrastructure hosting cost, on one problem.

The priority I'm thinking right now of is

1. mypy
2. Other Python type checkers such as (pyright, pyre-check, etc.)
3. Other Python related tools such as (flake8)
4. Running Python's code itself

I'm okay to start exploring the option 2 as you already opened PRs like #225 but I may spend my time on something like #229 #231 first to make it easier to extend mypy Playground further.

**Comment by KotlinIsland** [comment]
I'm not interested in this anymore.
