### ISSUE TITLE
mypy 0.981 is released

### ISSUE THREAD

**Issue by hauntsaninja** [ymyzk/mypy-playground#232]
Thanks again for maintaining this! Also I think the mypy "master" version could use an update (#158 / #162)

**Comment by ymyzk** [comment]
Thanks, I'll trigger GitHub Actions for adding 0.981.

* Add 0.981: #233
* Update `master`: https://github.com/ymyzk/mypy-playground/actions/runs/3143117583
* Update `latest`: https://github.com/ymyzk/mypy-playground/actions/runs/3143133821
* Deploy `0.981`: https://github.com/ymyzk/mypy-playground/actions/runs/3143133821

**Comment by ymyzk** [comment]
mypy 0.981 should be available now: https://mypy-play.net/?mypy=0.981&python=3.10&flags=version
