### ISSUE TITLE
Run button seems to reset code

### ISSUE THREAD

**Issue by hauntsaninja** [ymyzk/mypy-playground#236]
Playground seems sort of broken. Hitting the run button resets to whatever code was in the playground on page load.

**Comment by nrser** [comment]
Just came to check here 'cause I'm seeing the same thing (online at https://mypy-play.net/?mypy=latest&python=3.10).

I'm on:

-   macOS Monterey 12.6
-   Firefox 105.0.1 (64-bit)

**Comment by ymyzk** [comment]
It took a while but I could rollback the change. The older version's image is available at https://hub.docker.com/layers/ymyzk/mypy-playground/neutrino/images/sha256-38a56a8ee14d8a32c54880689a247a2a595b2e0d7b6aeef08ae9e0c16bbe6085?context=repo for the time being.
