### ISSUE TITLE
Error: Invalid syntax; you likely need to run mypy using Python 3.12 or newer

### ISSUE THREAD

**Issue by InSyncWithFoo** [ymyzk/mypy-playground#478]
This happens even if I already choose Python 3.12 _and_ the master branch of mypy.

A sample snippet ([playground](https://mypy-play.net/?mypy=master&python=3.12&gist=adc5c09be7cb839a0d68171147d5a51a)):

```py
class C[T: float]:
    pass

type Foo = str | int
```

```none
Failed (exit code: 2) (1964 ms)
main.py:1: error: invalid syntax; you likely need to run mypy using Python 3.12 or newer  [syntax]
Found 1 error in 1 file (errors prevented further checking)
```

**Comment by ymyzk** [comment]
Thanks for filing an issue. As mypy-play.net is using Cloud Functions v1 to run mypy and its latest version is Python 3.11, we're seeing this issue https://cloud.google.com/functions/docs/concepts/python-runtime
