### ISSUE TITLE
(🎁) add pre-commit.ci to the project

### ISSUE THREAD

**Issue by KotlinIsland** [ymyzk/mypy-playground#490]
a lot of projects use it and it works very well in my experience.

https://pre-commit.ci/
https://github.com/marketplace/pre-commit-ci

**Comment by ymyzk** [comment]
Thanks for the suggestion. Currently, we already run pre-commit using GitHub Actions + tox. There may benefit to use pre-commit.ci in addition to the GitHub Actions, but I don't feel that's necessarily a high priority for this project. I'd rather reserve time for implement features requested in issues.

**Comment by KotlinIsland** [comment]
Pre-conmit.ci is simply a GitHub app that us added to the project, it would only take 10 seconds to do.

It has the capability to automatically fix issues in a PR (formatting/linting) and commit the fixes onto the branch.

It also runs a lot faster than pre-commit in a GitHub action.

**Comment by KotlinIsland** [comment]
i hate precommit now, the guy that runs it is a horrible individual
