### ISSUE TITLE
Adding a link to mypy repo README

### ISSUE THREAD

**Issue by ilevkivskyi** [ymyzk/mypy-playground#56]
Are you OK if we add a link to this web site to mypy README?

See https://github.com/python/mypy/pull/6510

**Comment by ilevkivskyi** [comment]
@ymyzk Sorry for pinging, are you OK with merging the above PR in mypy?

**Comment by ymyzk** [comment]
@ilevkivskyi, sorry for my slow response.

It's completely fine with me. Thank you very much for adding a link!

**Comment by ilevkivskyi** [comment]
OK thanks, no problem, I will merge the PR.
