### ISSUE TITLE
Add `--warn-unreachable` flag

### ISSUE THREAD

**Issue by jack1142** [ymyzk/mypy-playground#72]

**Comment by ymyzk** [comment]
@jack1142 thanks for pointing it out! Added an option and deployed to mypy-play.net."
Example: https://mypy-play.net/?mypy=latest&python=3.8&flags=warn-unreachable&gist=4dc572f1a1fcb56a11fd9f5d7e080d59

**Comment by jack1142** [comment]
@ymyzk Sure, no problem, thanks for adding it so quickly :)
