### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by InSyncWithFoo** [ymyzk/mypy-playground#720]
The site seems to have been down since a few days ago. I get HTTP 522 everytime I try to access it.

**Comment by ymyzk** [comment]
Thanks for the report! I'll look into it now. Due to a personal reason, the monitoring system for the site has been stopped for a few days and that's why it took extra time to catch this.

**Comment by ymyzk** [comment]
The site should be back now. I also configured another external monitoring service so that we can notice the issue sooner next time. 🙂
