### ISSUE TITLE
Support for Python2.7 is broken

### ISSUE THREAD

**Issue by tmr232** [ymyzk/mypy-playground#726]
Current versions of mypy (>=0.980) no longer support Python2.7. This means that support on the website is effectively broken.

I don't know if it's better to just remove 2.7 entirely, or add old mypy, but the current situation is confusing as it _seems_ to support 2.7 until you actually run it.

**Comment by ymyzk** [comment]
Thanks for filing a ticket. As mypy-play.net doesn't host mypy versions older than 0.980 anymore, I think it's fair to remove Python 2.7 from the default configuration.

If there's a user who really need to run an older version of mypy on mypy Playground to test Python 2.7 code, they can update this configuration to add Python 2.7 back to the list: https://github.com/ymyzk/mypy-playground/blob/55a118bd9306cfb8d1ff8617483b11134d013168/app/config.toml#L5

**Comment by tmr232** [comment]
Thanks!
