### ISSUE TITLE
Add support for `--enable-incomplete-feature=InlineTypedDict`

### ISSUE THREAD

**Issue by sobolevn** [ymyzk/mypy-playground#785]
Right now there's no such feature: 
<img width="541" alt="Снимок экрана 2024-11-18 в 17 58 52" src="https://github.com/user-attachments/assets/c892ba3a-de35-4fa1-84c7-f72f6839e3c9">

See https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-enable-incomplete-feature

**Comment by ymyzk** [comment]
Thanks for the heads-up. The option is added and I plan to deploy a new version to mypy-play.net soon.
